import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";
import HeaderMobile from "@/app/components/header-mobile";
import SideNav from "@/app/components/sidenav";
import MarginWidthWrapper from "@/app/components/margin-width-wrapper";
import PageWrapper from "@/app/components/page-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Boeing Inventory Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-200 min-h-screen">
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header/>
              <HeaderMobile />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
